#!/bin/bash
# Generate .env file from Terraform outputs
# Run this after 'terraform apply' to sync your local .env

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

# Change to infra directory
cd "$(dirname "$0")/../infra"

# Check terraform is initialized
if [ ! -d ".terraform" ]; then
    echo "Error: Terraform not initialized. Run 'terraform init' first."
    exit 1
fi

log_info "Reading Terraform outputs..."

# Get values from terraform
PROJECT_ID=$(terraform output -raw gcs_bucket_name 2>/dev/null | sed 's/-fund-documents$//' || echo "")
DATA_STORE_ID=$(terraform output -raw vertex_search_data_store_id 2>/dev/null || echo "fund-knowledge-base")
ENGINE_ID=$(terraform output -raw vertex_search_engine_id 2>/dev/null || echo "fund-search-engine")
BUCKET_NAME=$(terraform output -raw gcs_bucket_name 2>/dev/null || echo "")

if [ -z "$PROJECT_ID" ]; then
    echo "Error: Could not read terraform outputs. Run 'terraform apply' first."
    exit 1
fi

# Check for existing .env
ENV_FILE="../.env"
if [ -f "$ENV_FILE" ]; then
    log_warn "Existing .env found. Backing up to .env.backup"
    cp "$ENV_FILE" "../.env.backup"
fi

# Check for existing API key to preserve it
EXISTING_API_KEY=""
if [ -f "$ENV_FILE" ]; then
    EXISTING_API_KEY=$(grep "^GOOGLE_API_KEY=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2 || echo "")
fi

# Generate .env
log_info "Generating .env file..."

cat > "$ENV_FILE" << EOF
# Generated by scripts/generate_env.sh from Terraform outputs
# Regenerate with: ./scripts/generate_env.sh

# Environment
ENVIRONMENT=dev

# GCP Project
GCP_PROJECT_ID=${PROJECT_ID}
GCP_REGION=us-central1

# Gemini API Key (get from https://aistudio.google.com/app/apikey)
GOOGLE_API_KEY=${EXISTING_API_KEY:-REPLACE_WITH_YOUR_API_KEY}

# Vertex AI Search (from Terraform)
VERTEX_SEARCH_DATA_STORE_ID=${DATA_STORE_ID}
VERTEX_SEARCH_ENGINE_ID=${ENGINE_ID}

# GCS Bucket (from Terraform)
GCS_BUCKET_NAME=${BUCKET_NAME}

# Optional settings
GEMINI_MODEL=gemini-2.5-flash
SYNC_PDFS_IN_DEV=false
PDF_BASE_URL=
EOF

log_info "Generated .env file at $(realpath "$ENV_FILE")"
echo ""
echo "Values from Terraform:"
echo "  PROJECT_ID:    ${PROJECT_ID}"
echo "  DATA_STORE_ID: ${DATA_STORE_ID}"
echo "  ENGINE_ID:     ${ENGINE_ID}"
echo "  BUCKET_NAME:   ${BUCKET_NAME}"
echo ""

if [ "$EXISTING_API_KEY" = "" ] || [ "$EXISTING_API_KEY" = "REPLACE_WITH_YOUR_API_KEY" ]; then
    log_warn "Don't forget to add your GOOGLE_API_KEY to .env!"
    echo "  Get one from: https://aistudio.google.com/app/apikey"
else
    log_info "Preserved existing GOOGLE_API_KEY"
fi
