#!/bin/bash
# Generate .env file from Terraform outputs
# Run this after 'terraform apply' to sync your local .env

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

# Change to infra directory
cd "$(dirname "$0")/../infra"

# Check terraform is initialized
if [ ! -d ".terraform" ]; then
    echo "Error: Terraform not initialized. Run 'terraform init' first."
    exit 1
fi

log_info "Reading Terraform outputs..."

# Get values from terraform
SERVICE_ACCOUNT=$(terraform output -raw service_account_email 2>/dev/null || echo "")

# Try to get project ID from gcloud
PROJECT_ID=$(gcloud config get-value project 2>/dev/null || echo "")

if [ -z "$PROJECT_ID" ]; then
    echo "Error: Could not determine project ID. Run 'gcloud config set project YOUR_PROJECT_ID' first."
    exit 1
fi

# Check for existing .env
ENV_FILE="../.env"
if [ -f "$ENV_FILE" ]; then
    log_warn "Existing .env found. Backing up to .env.backup"
    cp "$ENV_FILE" "../.env.backup"
fi

# Check for existing API key to preserve it
EXISTING_API_KEY=""
if [ -f "$ENV_FILE" ]; then
    EXISTING_API_KEY=$(grep "^GOOGLE_API_KEY=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2 || echo "")
fi

# Check for existing FAISS path to preserve it
EXISTING_FAISS_PATH=""
if [ -f "$ENV_FILE" ]; then
    EXISTING_FAISS_PATH=$(grep "^FAISS_INDEX_PATH=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2 || echo "")
fi

# Generate .env
log_info "Generating .env file..."

cat > "$ENV_FILE" << EOF
# Generated by scripts/generate_env.sh from Terraform outputs
# Regenerate with: ./scripts/generate_env.sh

# Environment
ENVIRONMENT=dev

# GCP Project
GCP_PROJECT_ID=${PROJECT_ID}
GCP_REGION=us-central1

# Gemini API Key (get from https://aistudio.google.com/app/apikey)
GOOGLE_API_KEY=${EXISTING_API_KEY:-REPLACE_WITH_YOUR_API_KEY}

# Local Vector Search (FAISS)
FAISS_INDEX_PATH=${EXISTING_FAISS_PATH:-./faiss_index}

# Optional settings
GEMINI_MODEL=gemini-2.5-flash
PDF_BASE_URL=
EOF

log_info "Generated .env file at $(realpath "$ENV_FILE")"
echo ""
echo "Values:"
echo "  PROJECT_ID:      ${PROJECT_ID}"
echo "  FAISS_INDEX_PATH: ${EXISTING_FAISS_PATH:-./faiss_index}"
echo ""

if [ "$EXISTING_API_KEY" = "" ] || [ "$EXISTING_API_KEY" = "REPLACE_WITH_YOUR_API_KEY" ]; then
    log_warn "Don't forget to add your GOOGLE_API_KEY to .env!"
    echo "  Get one from: https://aistudio.google.com/app/apikey"
else
    log_info "Preserved existing GOOGLE_API_KEY"
fi
